services:
  - type: web
    name: pizza-system-ai
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install .
    startCommand: python -m uvicorn pizza_app.api:app --host 0.0.0.0 --port 8082
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8082
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: OPENAI_API_KEY
        sync: false